apiVersion: v1
baseDomain: ${baseDomain}
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    azure:
      type: ${worker-instance-type}
      osDisk:
        diskSizeGB: 256
  replicas: ${workerNodeCount}
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      type: ${master-instance-type}
      osDisk:
        diskSizeGB: 256
  replicas: ${masterNodeCount}
metadata:
  creationTimestamp: null
  name: ${clustername}
networking:
  clusterNetwork:
  - cidr: ${cluster-network-cidr}
    hostPrefix: ${host-prefix}
  machineNetwork:
  - cidr: ${virtual-network-cidr}
  networkType: OpenShiftSDN
  serviceNetwork:
  - ${service-network-cidr}
platform:
  azure:
    baseDomainResourceGroupName: ${baseDomainResourceGroupName}
    region: ${region}
    networkResourceGroupName: ${networkResourceGroupName}
    virtualNetwork: ${virtualNetwork}
    controlPlaneSubnet: ${controlPlaneSubnet}
    computeSubnet: ${computeSubnet}
publish: ${private-public}
pullSecret: '${pullSecret}'
sshKey: |
  ${sshKey}