apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefiles-premium
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
  networkEndpointType: privateEndpoint
  location: $deployRegion
  skuName: Premium_LRS
  storageAccount: $AZURE_STORAGE_ACCOUNT_NAME
  resourceGroup: $resourceGroupName
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true