---

# 1. Failure conditions
# -----------------------------------------------------------------------------
- name: "fyre : Fail if required properties are not provided"
  assert:
    that:
      - fyre_quota_type is defined and fyre_quota_type != ""
      - fyre_quota_type is in ['quick_burn', 'product_group']
      - fyre_product_id is defined and fyre_product_id != ""
      - fyre_username is defined and fyre_username != ""
      - fyre_password is defined and fyre_password != ""

- name: "fyre : Fail if required properties are not provided (quickburn)"
  when: fyre_quota_type == "quick_burn"
  assert:
    that: fyre_cluster_size is defined and fyre_cluster_size != ""


# 2. Debug Info
# -----------------------------------------------------------------------------
- name: "fyre : Debug information"
  debug:
    msg:
      - "Cluster name ................. {{ cluster_name }}"
      - "Cluster type ................. {{ cluster_type }}"
      - "Cluster platform ............. {{ cluster_platform }}"
      - "OCP version .................. {{ ocp_version }}"
      - "Username ..................... {{ fyre_username }}"
      - "Fyre product ID .............. {{ fyre_product_id }}"
      - "Fyre Quota Type .............. {{ fyre_quota_type }}"
      # Quickburn specific
      - "Fyre cluster size ............ {{ fyre_cluster_size | default('<undefined>', true) }}"
      # Product Group specific
      - "Worker count ................. {{ fyre_worker_count | default('<undefined>', true) }}"
      - "Worker CPU ................... {{ fyre_worker_cpu | default('<undefined>', true) }}"
      - "Worker memory ................ {{ fyre_worker_memory | default('<undefined>', true) }}"


# 3. Determine whether there is already an environment running
# -----------------------------------------------------------------------------
- name: "fyre : Check if cluster already exists"
  uri:
    url: "https://ocpapi.svl.ibm.com/v1/ocp/{{cluster_name}}"
    user: "{{fyre_username}}"
    password: "{{fyre_password}}"
    method: GET
    force_basic_auth: yes
    validate_certs: false
  register: _cluster_exist
  failed_when: _cluster_exist.status == 403


# 4. Deploy the OCP+ cluster
# -----------------------------------------------------------------------------
- name: "fyre : Create new OCP+ cluster"
  when: _cluster_exist.json.cluster_count is not defined
  vars:
    fyre_template_name: "templates/fyre/{{ fyre_quota_type }}.json.j2"
  uri:
    url: https://ocpapi.svl.ibm.com/v1/ocp/
    user: "{{ fyre_username }}"
    password: "{{ fyre_password }}"
    method: POST
    body: "{{ lookup('template', fyre_template_name) }}"
    force_basic_auth: yes
    body_format: json
    validate_certs: false


# 5. Track the progress of the deployment
# -----------------------------------------------------------------------------
- name: "fyre : Follow deployment status (2 minute intervals)"
  uri:
    url: "https://ocpapi.svl.ibm.com/v1/ocp/{{ cluster_name }}/status"
    user: "{{ fyre_username }}"
    password: "{{ fyre_password }}"
    method: GET
    force_basic_auth: yes
    validate_certs: false
  register: _result
  until:
    - _result.json is defined
    - _result.json.deployed_status == 'deployed'
  retries: 60 # 60 * 2 minutes = 2 hours
  delay: 120 # Every 2 minutes
