---
- name: Create gce-pd-ssd storage class
  hosts: localhost
  gather_facts: no
  tasks:
  # Create storage class
  - name: create gce-pd-ssd storage class
    kubernetes.core.k8s:
      definition:
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: gce-pd-ssd
        provisioner: kubernetes.io/gce-pd
        parameters:
          type: pd-ssd
        volumeBindingMode: WaitForFirstConsumer
        reclaimPolicy: Delete
      wait: yes

      